<?php

namespace ArtificialImageGenerator;

defined( 'ABSPATH' ) || exit; // Exit if accessed directly.

/**
 * Class Generator.
 *
 * Central service for turning an image template into a rendered file and, from
 * there, into a Media Library attachment. Both the automatic `save_post`
 * generator and the REST endpoint go through this class so the mapping from
 * template meta to render arguments lives in exactly one place.
 *
 * @since 1.5.0
 * @package ArtificialImageGenerator
 */
class Generator {

	/**
	 * Meta key flagging an attachment as generated by this plugin.
	 *
	 * Stored as a simple '1' so it can be used in a meta query.
	 *
	 * @var string
	 * @since 1.5.0
	 */
	const GENERATED_META = '_aimg_generated';

	/**
	 * Meta key holding the provenance details of a generated attachment.
	 *
	 * @var string
	 * @since 1.5.0
	 */
	const GENERATED_DATA_META = '_aimg_generated_data';

	/**
	 * Build the render arguments for a template.
	 *
	 * Reads the template meta and resolves overlay attachment IDs to absolute
	 * paths, picking a single overlay at random when several are configured.
	 *
	 * @param int    $template_id Template post ID.
	 * @param string $title       Title rendered onto the image. Falls back to the template title.
	 *
	 * @since 1.5.0
	 * @return array|false Render arguments, or false when the template is invalid.
	 */
	public static function get_render_args( $template_id, $title = '' ) {
		$template = aimg_get_template( $template_id );

		if ( ! $template ) {
			return false;
		}

		$template_id = (int) $template->ID;

		$colors = get_post_meta( $template_id, '_aimg_bg_colors', true );
		if ( is_string( $colors ) ) {
			$colors = array_filter( array_map( 'trim', explode( ',', $colors ) ) );
		}

		$args = array(
			'template_id' => $template_id,
			'title'       => '' !== trim( (string) $title ) ? $title : $template->post_title,
			'colors'      => is_array( $colors ) ? $colors : array(),
			'width'       => (int) get_post_meta( $template_id, '_aimg_width', true ),
			'height'      => (int) get_post_meta( $template_id, '_aimg_height', true ),
			'overlays'    => self::get_overlay_paths( $template_id ),
		);

		/**
		 * Filter the arguments used to render an image from a template.
		 *
		 * @param array $args        Render arguments.
		 * @param int   $template_id Template post ID.
		 *
		 * @since 1.5.0
		 */
		return apply_filters( 'aimg_template_render_args', $args, $template_id );
	}

	/**
	 * Resolve a template's overlay images to absolute paths.
	 *
	 * Returns at most one overlay: when a template stores several, one is picked
	 * at random so repeated renders vary.
	 *
	 * @param int $template_id Template post ID.
	 *
	 * @since 1.5.0
	 * @return array List of absolute file paths.
	 */
	public static function get_overlay_paths( $template_id ) {
		if ( 'yes' !== get_post_meta( $template_id, '_aimg_is_overlay_image', true ) ) {
			return array();
		}

		$overlay_images = json_decode( (string) get_post_meta( $template_id, '_aimg_overlay_images', true ) );

		if ( ! is_array( $overlay_images ) ) {
			return array();
		}

		$paths = array();
		foreach ( $overlay_images as $id ) {
			$path = get_attached_file( (int) $id );
			if ( $path && file_exists( $path ) ) {
				$paths[] = $path;
			}
		}

		// Keep only a single overlay when several are configured.
		if ( count( $paths ) > 1 ) {
			$paths = array( $paths[ array_rand( $paths ) ] );
		}

		return $paths;
	}

	/**
	 * Render an image from a template.
	 *
	 * @param int    $template_id Template post ID.
	 * @param string $title       Title rendered onto the image.
	 *
	 * @since 1.5.0
	 * @return string|false Absolute path to the rendered file, or false on failure.
	 */
	public static function render( $template_id, $title = '' ) {
		$args = self::get_render_args( $template_id, $title );

		if ( ! $args ) {
			return false;
		}

		return aimg_generate_thumbnail( $args );
	}

	/**
	 * Pick a published template at random.
	 *
	 * @since 1.5.0
	 * @return int Template post ID, or 0 when no template is available.
	 */
	public static function get_random_template_id() {
		$templates = get_posts(
			array(
				'post_type'        => 'aimg_template',
				'posts_per_page'   => 1,
				'post_status'      => 'publish',
				'fields'           => 'ids',
				'orderby'          => 'rand',
				'suppress_filters' => false,
			)
		);

		if ( empty( $templates ) || ! is_array( $templates ) ) {
			return 0;
		}

		return (int) reset( $templates );
	}

	/**
	 * Import a rendered file into the Media Library.
	 *
	 * @param string $filepath Absolute path to a file inside the uploads directory.
	 * @param array  $args     {
	 *     Optional. Attachment arguments.
	 *
	 *     @type string $title      Attachment title. Defaults to the file name.
	 *     @type string $alt        Alt text. Defaults to the title.
	 *     @type int    $parent     Parent post ID. Default 0.
	 *     @type array  $provenance Provenance details stored on the attachment.
	 * }
	 *
	 * @since 1.5.0
	 * @return int|\WP_Error Attachment ID on success.
	 */
	public static function create_attachment( $filepath, $args = array() ) {
		if ( empty( $filepath ) || ! file_exists( $filepath ) ) {
			return new \WP_Error(
				'aimg_missing_file',
				__( 'The generated image could not be found on disk.', 'artificial-image-generator' ),
				array( 'status' => 500 )
			);
		}

		require_once ABSPATH . 'wp-admin/includes/image.php';

		// WordPress only stores a relative `_wp_attached_file` when the path uses
		// the same separator style as wp_upload_dir().
		$filepath = aimg_uploads_path( $filepath );

		$args = wp_parse_args(
			$args,
			array(
				'title'      => '',
				'alt'        => '',
				'parent'     => 0,
				'provenance' => array(),
			)
		);

		$title = '' !== $args['title'] ? $args['title'] : basename( $filepath );
		$mime  = function_exists( 'mime_content_type' ) ? mime_content_type( $filepath ) : '';

		$attachment_id = wp_insert_attachment(
			array(
				'post_mime_type' => $mime ? $mime : 'image/png',
				'post_title'     => $title,
				'post_content'   => '',
				'post_status'    => 'inherit',
			),
			$filepath,
			(int) $args['parent'],
			true
		);

		if ( is_wp_error( $attachment_id ) ) {
			return $attachment_id;
		}

		$metadata = wp_generate_attachment_metadata( $attachment_id, $filepath );
		wp_update_attachment_metadata( $attachment_id, $metadata );

		$alt = '' !== $args['alt'] ? $args['alt'] : $title;
		update_post_meta( $attachment_id, '_wp_attachment_image_alt', sanitize_text_field( $alt ) );

		self::mark_generated( $attachment_id, $args['provenance'] );

		return (int) $attachment_id;
	}

	/**
	 * Flag an attachment as generated by this plugin and record how it was made.
	 *
	 * The flag makes generated images queryable; the details make regeneration,
	 * auditing and cost reporting possible later on.
	 *
	 * @param int   $attachment_id Attachment ID.
	 * @param array $provenance    {
	 *     Optional. Provenance details.
	 *
	 *     @type string $source      'template' or 'prompt'.
	 *     @type int    $template_id Template used, when rendered from a template.
	 *     @type string $prompt      Prompt used, when generated from a prompt.
	 *     @type string $provider    Service that produced the image.
	 *     @type string $model       Model identifier.
	 * }
	 *
	 * @since 1.5.0
	 * @return void
	 */
	public static function mark_generated( $attachment_id, $provenance = array() ) {
		$attachment_id = absint( $attachment_id );

		if ( ! $attachment_id ) {
			return;
		}

		$provenance = wp_parse_args(
			$provenance,
			array(
				'source'      => 'template',
				'template_id' => 0,
				'prompt'      => '',
				'provider'    => '',
				'model'       => '',
			)
		);

		$provenance['template_id'] = absint( $provenance['template_id'] );
		$provenance['version']     = defined( 'AIMG_VERSION' ) ? AIMG_VERSION : '';
		$provenance['generated']   = gmdate( 'c' );

		update_post_meta( $attachment_id, self::GENERATED_META, '1' );
		update_post_meta( $attachment_id, self::GENERATED_DATA_META, $provenance );

		/**
		 * Fires after an image generated by the plugin has been added to the Media Library.
		 *
		 * @param int   $attachment_id Attachment ID.
		 * @param array $provenance    Provenance details stored on the attachment.
		 *
		 * @since 1.5.0
		 */
		do_action( 'aimg_generated_image', $attachment_id, $provenance );
	}
}
